version: "3.8"
services:
  nodejs:
    build: 
      context: .
    image: wahyu12345/nodejs-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=rootuser
      - MYSQL_PASS=rootpass
      - MYSQL_DB=db
    volumes:
      - .:/app
    ports:
      - 30001:5000
    container_name: moe-nodejs-app
  mysql:
    image: mysql:latest
    cap_add:
      - SYS_NICE 
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=rootuser
      - MYSQL_PASSWORD=rootpass
      - MYSQL_DATABASE=db
    container_name: moe-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    networks:
      - backend
    restart: always
    ports:
      - 30002:80
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend:
